"""
Career Catalyst — Ghost PR Reviewer
====================================
Runs on every Pull Request via GitHub Actions.
Reads the PR diff + DEFAULT_RUBRIC.md, calls an AI model using the
CareerCatalyst agent persona, and posts a Level-Up critique comment.

Environment variables (set by the workflow):
  GITHUB_TOKEN       – GitHub Actions token (required for PR comment + GitHub Models fallback)
  PR_NUMBER          – Pull request number
  GITHUB_REPOSITORY  – "owner/repo" string
  AI_API_KEY         – Optional. Custom AI provider key (OpenAI, Anthropic, etc.)
                       Falls back to GITHUB_TOKEN for GitHub Models if unset.
  AI_BASE_URL        – Optional. Custom API base URL.
                       Defaults to GitHub Models: https://models.inference.ai.azure.com
  AI_MODEL           – Optional. Model identifier.
                       Defaults to "gpt-4o-mini".

Dependencies: see .github/scripts/requirements.txt (openai, PyGithub)
"""

from __future__ import annotations

import os
import sys
import textwrap

from github import Github, GithubException
from openai import APIError as OpenAIAPIError
from openai import OpenAI

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

GITHUB_TOKEN = os.environ["GITHUB_TOKEN"]
PR_NUMBER = int(os.environ["PR_NUMBER"])
REPO_NAME = os.environ["GITHUB_REPOSITORY"]

AI_API_KEY = os.environ.get("AI_API_KEY") or GITHUB_TOKEN
AI_BASE_URL = os.environ.get("AI_BASE_URL") or "https://models.inference.ai.azure.com"
AI_MODEL = os.environ.get("AI_MODEL") or "gpt-4o-mini"

MAX_DIFF_CHARS = 8_000   # ~2k tokens at ~4 chars/token — keeps the prompt well within
MAX_RUBRIC_CHARS = 6_000  # gpt-4o-mini's 128k-token context while controlling API cost

# ---------------------------------------------------------------------------
# Load rubric
# ---------------------------------------------------------------------------

RUBRIC_PATH = "docs/DEFAULT_RUBRIC.md"

def load_rubric() -> str:
    try:
        with open(RUBRIC_PATH, encoding="utf-8") as fh:
            content = fh.read()
        return content[:MAX_RUBRIC_CHARS]
    except FileNotFoundError:
        return "(Rubric file not found — using built-in defaults.)"

# ---------------------------------------------------------------------------
# Build PR diff summary
# ---------------------------------------------------------------------------

def build_diff_summary(pr) -> str:
    files = list(pr.get_files())
    parts: list[str] = []
    for f in files[:25]:  # Cap at 25 files to stay within limits
        patch = f.patch or "(binary or no diff)"
        parts.append(
            f"=== {f.filename}  [+{f.additions} / -{f.deletions}] ===\n{patch}"
        )
    return "\n\n".join(parts)[:MAX_DIFF_CHARS]

# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = textwrap.dedent("""\
    You are CareerCatalyst — a Staff-level engineering mentor embedded in the
    code review process. Your purpose is not just to catch bugs; it is to help
    engineers think and operate at the *next* level of their career ladder.

    You have deep knowledge of the following engineering leveling rubric:

    {rubric}

    When reviewing a pull request:
    1. DETECT the level of thinking demonstrated (use rubric level codes:
       E1, E2, E3, S1, S2, ST, SS, PR).
    2. IDENTIFY the primary signal — the one thing that most clearly reveals
       the current level.
    3. SUGGEST one concrete, specific change that would elevate the PR to
       the next rubric level. Be precise: name the file, pattern, or concept.
    4. OPTIONALLY highlight one thing done especially well (keep it brief).

    Be direct and specific. Do not be vague or generic. Reference actual code
    from the diff when making suggestions. Keep the total response under
    400 words. Format as Markdown.
""")

USER_TEMPLATE = textwrap.dedent("""\
    ## Pull Request: {title}

    **Author:** {author}
    **Base → Head:** `{base}` → `{head}`
    **Files changed:** {file_count}  |  **+{additions} / -{deletions}**

    ### Diff (truncated to {max_chars} chars)

    {diff}
""")

COMMENT_TEMPLATE = textwrap.dedent("""\
    ## 🚀 Career Catalyst — Level-Up Code Review

    {critique}

    ---
    *Generated by [Career Catalyst](https://github.com/aneudy1702/career-catalyst) · \
    Benchmarked against the [Engineering Rubric](docs/DEFAULT_RUBRIC.md)*
""")

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    gh = Github(GITHUB_TOKEN)
    repo = gh.get_repo(REPO_NAME)
    pr = repo.get_pull(PR_NUMBER)

    rubric = load_rubric()
    diff_summary = build_diff_summary(pr)
    files = list(pr.get_files())

    user_message = USER_TEMPLATE.format(
        title=pr.title,
        author=pr.user.login,
        base=pr.base.ref,
        head=pr.head.ref,
        file_count=len(files),
        additions=pr.additions,
        deletions=pr.deletions,
        max_chars=MAX_DIFF_CHARS,
        diff=diff_summary,
    )

    client = OpenAI(base_url=AI_BASE_URL, api_key=AI_API_KEY)

    try:
        completion = client.chat.completions.create(
            model=AI_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT.format(rubric=rubric)},
                {"role": "user", "content": user_message},
            ],
            max_tokens=1_200,
            temperature=0.4,
        )
        critique = completion.choices[0].message.content or "(No critique generated.)"
    except (OpenAIAPIError, OSError) as exc:
        print(f"WARNING: AI API call failed ({exc}). Posting fallback comment.", file=sys.stderr)
        critique = textwrap.dedent(f"""\
            > ⚠️ The Career Catalyst AI review could not be completed automatically.
            >
            > **Reason:** `{exc}`
            >
            > To run the review manually, ensure `AI_API_KEY` (or GitHub Models access)
            > is configured in your repository secrets, then re-run the workflow.
        """)

    comment_body = COMMENT_TEMPLATE.format(critique=critique)
    pr.create_issue_comment(comment_body)
    print(f"✅ Career Catalyst comment posted to PR #{PR_NUMBER}.")


if __name__ == "__main__":
    main()
